# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

viral_dynamics_aim3 <- function(Agent, time_0, time_final, h, Num_Loci, m, k, r_base, d, f_M, f_L, d_M, d_L, p, p_M, p_L, M_act, L_act, V0, V_peak, t_peak, t_acute, V_AIDS, mu, cost_DT, additive_fitness, Drug_DT, SPVL, prog_rate, vl_increase_AIDS, Time_Inf, Immune_Response_Triggered, ChronicPhaseBegins, TherapyStarted, SecondLineTherapyStarted, Adherence1, Adherence2, Adherence3, Adherence4, Virus_DT, Interaction_Model_Drugs12, FC_DT, StochasticCut, cut, K, c, CD4, Drug1, Drug2, Drug3, Drug4, Dosing_Interval, Therapy_Type, stop_restart_DT, Aim3RoundingErrors) {
    .Call('_evonet_viral_dynamics_aim3', PACKAGE = 'evonet', Agent, time_0, time_final, h, Num_Loci, m, k, r_base, d, f_M, f_L, d_M, d_L, p, p_M, p_L, M_act, L_act, V0, V_peak, t_peak, t_acute, V_AIDS, mu, cost_DT, additive_fitness, Drug_DT, SPVL, prog_rate, vl_increase_AIDS, Time_Inf, Immune_Response_Triggered, ChronicPhaseBegins, TherapyStarted, SecondLineTherapyStarted, Adherence1, Adherence2, Adherence3, Adherence4, Virus_DT, Interaction_Model_Drugs12, FC_DT, StochasticCut, cut, K, c, CD4, Drug1, Drug2, Drug3, Drug4, Dosing_Interval, Therapy_Type, stop_restart_DT, Aim3RoundingErrors)
}

